spring:
  application:
    name: session-login-service
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

server:
  port: 8080
  error:
    include-message: always

